# Spring Boot Application Configuration
# 이 파일은 docker-compose.yml에서 볼륨 마운트로 사용됩니다.
# 필요에 따라 설정을 수정하세요.

spring:
  datasource:
    url: jdbc:mysql://13.124.54.126:3306/cmb_public?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cmb_public
    password: "cmb_public12#$"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool-WiseMapping
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED
      leak-detection-threshold: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        default_batch_fetch_size: 200
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        jakarta:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: classpath:ehcache.xml
  sql:
    init:
      mode: never

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  site:
    ui-base-url: ${UI_BASE_URL:https://www.cmberp.co.kr}
    api-base-url: ${API_BASE_URL:https://www.cmberp.co.kr}
  security:
    corsAllowedOrigins: ${CORS_ALLOWED_ORIGINS:https://www.cmberp.co.kr,http://www.cmberp.co.kr}
    # ERP 시스템 세션 연동 설정
    sessionUserIdBypassEnabled: true
    sessionUserIdAttribute: userId

logging:
  level:
    root: INFO
    com.wisemapping: DEBUG
  file:
    name: /app/logs/spring-boot.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

