spring:
  datasource:
    url: jdbc:mysql://61.97.187.218:3307/cmb_public?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cmb_public
    password: "ispark12#$"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool-WiseMapping
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED
      leak-detection-threshold: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        default_batch_fetch_size: 200
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        jakarta:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: classpath:ehcache.xml
  sql:
    init:
      mode: never

# ERP 시스템 연동을 위한 설정
app:
  site:
    ui-base-url: http://localhost:3000
    api-base-url: http://localhost:8081
  security:
    # ERP 시스템에서 접근할 수 있도록 CORS 설정
    corsAllowedOrigins: http://localhost:3000,http://localhost:8080

# 서버 포트 설정 (Docker 컨테이너 내부는 8080, 호스트는 8081로 매핑)
server:
  port: 8080

